### ISSUE TITLE
Would not open this URL: ~/code/learn/serverless-stack/ServerlessStack-v3.1.pdf

### ISSUE THREAD

**Issue by noahcoad** [noahcoad/open-url#39]
It should with just the cursor underneath, but it didn't.  It requires selecting the whole line.  Please fix so that just having the cursor under works.  I expect it's in the regex.

~/code/learn/serverless-stack/ServerlessStack-v3.1.pdf

**Comment by kylebebak** [comment]
@noahcoad 
Hey, thanks for reporting this =)

I think the problem was that we weren't running the path through [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser), which expands `~` and `~user`.

This is fixed in **1.1.0**. I just tried opening an almost identical path and it worked. Please re-open if it's not fixed for you!

<img width="503" alt="screen shot 2018-08-09 at 10 57 45 am" src="https://user-images.githubusercontent.com/1524088/43910906-ae405a2c-9bc3-11e8-9528-5c1a6d0b8307.png">
