### ISSUE TITLE
Opening files with no extension in the path or a leading underscore in a name

### ISSUE THREAD

**Issue by certainlyakey** [noahcoad/open-url#50]
Hi and thanks for a great plugin!

I've noticed that the plugin currently doesn't seem to work with local file paths that do not have a file extension in them or that have a leading underscore in their name. Such paths are used a lot with for example [SASS partials](https://sass-lang.com/guide) (`@import 'grid'` actuallly imports `_grid.scss`) or JS modules (`import { Component } from './search-input/search-input.component';` means `search-input.component.js`). 

Is there any workaround to open such files? If not then maybe you could consider adding support for it?

Thanks!

**Comment by kylebebak** [comment]
Hey, sorry for not responding until now... Glad you like the plugin!

Having open-url handle something like `@import 'grid'` by treating `grid` as though it were `_grid.scss` is probably out of scope.

`open-url` expands a selection until it reaches a delimiter char, like `'`, then takes the selection and looks for a file or folder that exists at that path (relative to the open file first, then to the project).

If there's no file at path `grid`, open-url doesn't know it should try `_grid.scss` instead. I can think of no good way for it to know that. Of course I'm open to suggestions.

However, the second use case is something I think we can solve, and that's definitely worth solving. We can add a setting, like `"module_file_extensions"`, which is a list of extensions, like `[".js", ".jsx", ".ts", ".tsx"]`. If `open-url` looks for a path like `./search-input/search-input.component` and finds nothing, it can then try `./search-input/search-input.component.<js|jsx|ts|tsx>` in order, and open the first one it finds.

I write a lot of JS and TS code, so this would be a useful feature for me as well.

**Comment by certainlyakey** [comment]
OK, thanks a lot! Glad you consider the second suggestion worthy.
Regarding the leading underscore use case, it's a feature of CSS preprocessors (SASS and LESS) that they will not compile `.scss` files with an underscore in their name to separate CSS files, but will instead include them into a global CSS file. In other words, leading underscore is not a convention, it's one of the basic rules in those languages. Some SASS files are essentially lists of imports, and absence of this feature makes it impossible to browse SASS codebase with the plugin. 

> If there's no file at path grid, open-url doesn't know it should try _grid.scss instead. I can think of no good way for it to know that. Of course I'm open to suggestions.

Maybe the plugin could have a user setting that would contain a set of leading characters to try if the file is not found using the exact name? So, if the setting contains '_!', then the plugin, having not found `grid.scss`, could try both `_grid.scss` and `!grid.scss` as well. I'm not sure how performant that would be though.

**Comment by kylebebak** [comment]
@certainlyakey 
I thought of something like that as well.

I'm glad you mentioned perf issues. If there were just a "file_prefixes" setting, there would be no perf issues, because even if you had 10 of them, checking 10 paths for the presence of a file takes any machine much less than 1ms (i.e., it's impossible to notice).

However, I'm going to push a release that adds other settings as well. I think `module_file_extensions` ought to have a more general name, like `file_suffixes`.

And there will also be a `search_paths` setting, that lets you specify path prefixes that you want to prepend to the entire file path and search as well (very useful for absolute imports in a JS project, for example).

This means there would be 3 additional settings, `file_prefixes`, `file_suffixes`, `search_paths`. If each of these had 5 items, there would 5^3 = 125 additional paths to check each time you run open-url. Would this hurt performance? I still kind of doubt it, but I guess I'll find out soon.

Anyways, sure, I'll add this setting as well. It seems like it could be useful. It might be nice to add a setting for general transformations of a file name, or more general transformations of an entire path, that does the work of the 3 settings I'm proposing above, but the truth is there's no good way to do it.

Given that settings are limited to JSON you can't run an arbitrary function on a path using settings. You could transform the path with arbitrary regular expressions, but in the vast majority of cases you'd want to do something like the two things you described above, i.e. prepend or append something to the file, so requiring users to use regex to do this doesn't make sense. No one would use the feature.

Anyway, done thinking out loud, and just going to say again that I'm convinced that adding these settings is a good idea.

**Comment by certainlyakey** [comment]
That's very good news! Looking forward to try the update out.

**Comment by kylebebak** [comment]
Ok, 2.6.0 takes care of this =)

Have a look at <https://github.com/noahcoad/open-url/#url--path-transforms>.

Let me know if you have any questions, going to close this.

**Comment by certainlyakey** [comment]
That's quite an awesome work that you've done, thanks! Works for me, for both use cases (SASS and JS/TS imports). Will keep reporting if I notice something unusual.
