### ISSUE TITLE
Open a file at a specified line

### ISSUE THREAD

**Issue by Karulp** [noahcoad/open-url#53]
Hello!

First of all, I want to thank for this package!
I use it a lot to open text files and web page and it is very efficient.

There is a functionnality I would like to use: open a file at a specified line with open-url.
For exemple, if there is "D:\path\to\my\file.txt:30" in a file text and I type ctrl+alt+u on it, Open-url open file.txt in sublime text at the line 30.

When I do this, a windows pop up with "subl: open file at line #" appears.
But no actions come after this window: If I click on the window, nothing happens. 
If I try to enter the number of the line where I want to go, nothing happens either.

I use sublime text version 3.2.2 and open-rul v2.7.0, on windows 10.

Is it just a configuration problem?
Or Open-url needs an other syntax that file:line_number?

I saw the lines below in the open-url settings, but I do not have enought skills in sublime-settings to understand what I have to modify.
  "other_custom_commands": [
    // { "label": "open with filezilla", "os": "osx", "pattern": "^ftp://", "commands": [ "open", "-a", "/Applications/FileZilla.app" ] },
    {
      "label": "subl: open file at line #",
      "pattern": ":[0-9]+$",
      "commands": ["subl"],
      "kwargs": { "cwd": "project_root" }
    }
  ]

Thanks!

**Comment by Karulp** [comment]
This is an enhancement, not a bug, but I cannot add the enhancement label.
Maybe I do not have the rights to do it?

**Comment by kylebebak** [comment]
@Karulp 

Hey, sorry for not answering until now, it's been a while since I've had time to look at this plugin. For this to work, [you need to install the Sublime Text CLI tool](https://www.sublimetext.com/docs/command_line.html), and make sure the `subl` executable is in your path

`subl` isn't part of the Open URL plugin, it's just the name of an executable that you can run on path that's matched by the regex in `pattern`
